"""Correct column name

Revision ID: 36cef5f4bc27
Revises: 6651fe09f67e
Create Date: 2024-05-09 17:33:42.505709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cef5f4bc27'
down_revision = '6651fe09f67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_color', sa.String(length=120), nullable=True))
        batch_op.drop_column('favourite_pizza')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_pizza', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('favourite_color')

    # ### end Alembic commands ###
