"""Add Post Model

Revision ID: 5a7ccd9130da
Revises: 88c90da12487
Create Date: 2024-05-10 14:21:20.609118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7ccd9130da'
down_revision = '88c90da12487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('slug')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('author')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
